### ISSUE TITLE
6.4跟7.2都测试了，好像不太行啊

### ISSUE THREAD

**Issue by 1136623363** [yd5513868/Pydroid-3-Premium#1]
![Screenshot_2024-06-08-01-57-26-17_084ab3bc34f7aa7ccff83653f52abafc.jpg](https://github.com/yepqqw/Pydroid-3-Premium/assets/72068332/0df2dd6d-22cf-48c3-83bc-4bdd7db4e0ce)

![Screenshot_2024-06-08-01-57-20-29_c759c44d10a956b96f85cc66750ff86e.jpg](https://github.com/yepqqw/Pydroid-3-Premium/assets/72068332/063d4bef-943d-4f67-845f-32bf80d43690)

**Comment by yepqqw** [comment]
> ![截图_2024-06-08-01-57-26-17_084ab3bc34f7aa7ccff83653f52abafc.jpg](https://private-user-images.githubusercontent.com/72068332/337748257-0df2dd6d-22cf-48c3-83bc-4bdd7db4e0ce.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3ODY3NzYsIm5iZiI6MTcxNzc4NjQ3NiwicGF0aCI6Ii83MjA2ODMzMi8zMzc3NDgyNTctMGRmMmRkNmQtMjJjZi00OGMzLTgzYmMtNGJkZDdkYjRlMGNlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDE4NTQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNTFkYjU2MjJhZTM5NzJiMDNkMjI2ZWZjZTYwMWJjNjFjYTY2ZTdlOTI4NjRiODNmMjZiZjI1MWQ0ZDA1ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GP-dxVwNuRE7MyXxWPHbAUxi7U8aajE-w4pVdfWneYM)
> 
> ![截图_2024-06-08-01-57-20-29_c759c44d10a956b96f85cc66750ff86e.jpg](https://private-user-images.githubusercontent.com/72068332/337748272-063d4bef-943d-4f67-845f-32bf80d43690.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3ODY3NzYsIm5iZiI6MTcxNzc4NjQ3NiwicGF0aCI6Ii83MjA2ODMzMi8zMzc3NDgyNzItMDYzZDRiZWYtOTQzZC00ZjY3LTg0NWYtMzJiZjgwZDQzNjkwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDE4NTQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZmFmNzk2YjZjNDlkODQxZmEzNWFmZjFlMmM0MjRlMmQ5MWYyOGNlNjkwNDNiMGIyNDAxOWE0ODFkYWU5ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2abTGefVA5ONHh4UTXD8P2GnrtUO4OB-lcl61ypZ2cU)

没有开启开关吧？
![Uploading Screenshot_2024-06-08-02-54-24-666_yep.python.hook.jpg…]()

**Comment by 1136623363** [comment]
![Screenshot_2024-06-08-02-56-54-17_866ce23fb8501bf58083983c840fb4a9.jpg](https://github.com/yepqqw/Pydroid-3-Premium/assets/72068332/ab1dec7e-0860-42c7-b5da-7d22c155737a)

开了呀，手机是一加ace2pro安卓14

**Comment by 1136623363** [comment]
![Screenshot_2024-06-08-02-56-54-17_866ce23fb8501bf58083983c840fb4a9.jpg](https://github.com/yepqqw/Pydroid-3-Premium/assets/72068332/490eed06-edff-4385-a95c-b537392b3c1a)

**Comment by 1136623363** [comment]
![Screenshot_2024-06-08-02-56-54-17_866ce23fb8501bf58083983c840fb4a9.jpg](https://github.com/yepqqw/Pydroid-3-Premium/assets/72068332/da29fb9c-5eda-4858-b5e0-7b34b14937e0)

**Comment by yepqqw** [comment]
重启下pydroid，安卓13-14都试了可以

**Comment by 1136623363** [comment]
> 重启下pydroid，安卓13-14都试了可以

😂不是，拿我当小孩吗，这些我都不会我还给你提啥issue

**Comment by yepqqw** [comment]
> > 重启下pydroid，安卓13-14都试了可以
> 
> 😂不是，拿我当小孩吗，这些我都不会我还给你提啥issue

复现不了，那您试试复制Lqwe/qweqwe/texteditor/p0;->u0()Z用算法助手返回true

**Comment by yepqqw** [comment]
> > 重启下pydroid，安卓13-14都试了可以
> 
> 😂不是，拿我当小孩吗，这些我都不会我还给你提啥issue

试试这个版本https://www.123pan.com/s/KhjA-I44g3.html
